export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FAILED_INGREDIENTS = 'FAILED_INGREDIENTS';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILED = 'PURCHASE_FAILED';
export const PURCHASE_LOAD = 'PURCHASE_LOAD';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_START = 'PURCHASE_START';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const ORDER_INIT = 'ORDER_INIT';

export const AUTH_START ='AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INIT_LOGOUT = 'AUTH_INIT_LOGOUT';
export const AUTH_TIMEOUT = 'AUTH_TIMEOUT';
export const AUTH_SINGOUT = 'AUTH_SINGOUT';
export const AUTH_USER = 'AUTH_USER ';
export const AUTH_CHECK = 'AUTH_CHECK';
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';